# ref ---------------------------------------------------------------------
# https://robinsonlabuzh.github.io/pasta/00-overview-latSOD.html


# Lattice data analysis – Summary -----------------------------------------
# In this vignette we will show:
# An overview of lattice data analysis methods for HTS-based data.
# This includes global metrics on the entire field of view and local variants thereof.
# The use case is a 10x Visium data set from McKellar et al. (2021).
# This overview is in parts based on the corresponding Voyager 10x Visium vignette.

# Introduction ------------------------------------------------------------
# In contrast to point pattern based methods, we can view the location of cells or spots as a fixed lattice and measure the corresponding marker expression at each location. HTS-based spatial transcriptomic technologies often produce data on a regular lattice (i.e., approximately evenly spaced spots or beads of uniform size and shape), whereas imaging-based technologies yield irregular lattice structures (i.e., with variable cell sizes and shapes, and non-uniform spacing).

# For the representation of the cells, we will rely in R on the SpatialFeatureExperiment package (see below for more details). For preprocessing of the dataset and code examples, we refer the reader to this 10x Visium vignette of the Voyager package (Moses et al. 2023). The Voyager package also provides wrapper functions around the package spdep (Pebesma and Bivand 2023) that work directly on the SpatialFeatureExperiment object. The package spdep is designed for the analysis of spatial data with lattice structure.

# For the implementation in Python we will rely on the the packages esda, pysal and squidpy (Rey and Anselin 2010; Palla et al. 2022). For the data representation we rely on the anndata structure (Virshup et al. 2024).

# libraries ---------------------------------------------------------------
suppressPackageStartupMessages({
  library(tidyverse)
  library(patchwork)
  library(Voyager)
  library(SpatialFeatureExperiment)
  library(SFEData)
  library(spdep)
  library(sf)
  library(stringr)
  library(tidyr)
  library(magrittr)
  library(scater)
  library(bluster)
  library(scico)
})

# parameters --------------------------------------------------------------
theme_set(theme_light())

roma_colors <- data.frame(roma_colors = scico::scico(256, palette = 'roma'))
write_csv(roma_colors , "../../data/roma_colors.csv")

# define the set of genes for the test
features <- c("Myh2", "Calr")

# Setup and Preprocessing -------------------------------------------------
# We will load a dataset by (McKellar et al. 2021) using the Visium technology (Ståhl et al. 2016). The data shows a sample taken from the tibialis anterior muscle of a mouse.

# Load the dataset
sfe <- SFEData::McKellarMuscleData(dataset = "full")

# Take spots that are covered with tissue
sfe_tissue <- sfe[, colData(sfe)$in_tissue]

# Filter out genes with no counts
sfe_tissue <- sfe_tissue[rowSums(counts(sfe_tissue)) > 0, ]

# Convert counts log-transformed normalized expression values
sfe_tissue <- scater::logNormCounts(sfe_tissue)

# ann <-  zellkonverter::SCE2AnnData(sfe_tissue)
# # Define the directory and file paths
# dir_path <- "../data"
# # Check if the directory exists, and create it if it doesn't
# if (!dir.exists(dir_path)) {
#   dir.create(dir_path)
# }
# anndata::write_h5ad(ann, "../data/McKellarMuscleData_processed.h5ad")

# save the object in case of future use
saveRDS(object = sfe_tissue,file = "../../out/object/sfe_McKellarMuscleData.rds")
# sfe_tissue <- readRDS(file = "../../out/object/sfe_McKellarMuscleData.rds")

# notice that at this point the graph slot is empty
sfe_tissue
spatialGraphs(sfe_tissue)

# SpatialFeatureExperiment (Moses et al. 2023) objects are an extension of the SpatialExperiment object (Righelli et al. 2022). It additionally contains geometric annotations that are encoded as simple features of the sf library (Pebesma and Bivand 2023).
# For Python we use the anndata object (Virshup et al. 2024).
sfe_tissue

# For example, the spots of the Visium dataset are stored as a simple feature collection.
colGeometry(sfe_tissue, "spotPoly") |> head()

# Lattice Data ------------------------------------------------------------
# Definition
# Lattice data refers to spatial data collected at locations arranged in a regular or irregular grid (lattice). Each location has a defined spatial unit, and the sampling locations are fixed rather than random. This approach contrasts with point pattern analysis, where we assume that the locations were generated by a stochastic process (Zuur, Ieno, and Smith 2007; Pebesma and Bivand 2023; Baddeley, Rubak, and Turner 2015).

# As can be seen below, the Visium dataset is a regular lattice. The color shows the number of counts detected in each Visium spot. In contrast, the outlines of individual cells after segmentation (e.g., from a higher resolution spatial omics assay) could be seen as an irregular lattice. As this dataset also contains (manual) segmentations of myofibers (muscle cells stored as myofiber_simplified), we will illustrate calculations based on irregular lattices of the myofiber segmentations.

# A plot using the plotSpatialFeature from Voyager
p <- plotSpatialFeature(sfe_tissue,
                        "nCounts",
                        annotGeometryName = "myofiber_simplified"
)

# This extracts the segmented cells
cells <- annotGeometry(sfe_tissue, "myofiber_simplified") |>
  st_geometry()

# We can also use ggplot and geom_sf to plot sf objects
q <- ggplot() +
  geom_sf(data = cells, fill = NA) +
  theme_void()

# Using `patchwork` to combine the plots
p | q

# Spatial weight matrix ---------------------------------------------------
# In lattice data analysis, a key concept is the spatial weight matrix, which models the spatial relationships between units in the lattice (i.e., spots or cells). Various methods exist for constructing this matrix, such as contiguity-based (direct neighbors), graph-based, or distance-based methods. (Getis 2009; Zuur, Ieno, and Smith 2007; Pebesma and Bivand 2023). The documentation of the package spdep gives an overview of the different methods.

# For Visium, the most straightforward way is to take the direct neighbours of each spot. This is done using the function findVisiumGraph.

colGraph(sfe_tissue, "visium") <- findVisiumGraph(sfe_tissue)
colGraph(sfe_tissue, "binary") <- findVisiumGraph(sfe_tissue, style = "B")

# notice that the graph slot has been filled with visium and binary
sfe_tissue
spatialGraphs(sfe_tissue)

plotColGraph(sfe_tissue,
             colGraphName = "visium",
             colGeometryName = "spotPoly"
) + theme_void()

# In an irregular lattice, the task of finding a spatial weight matrix is more complex, as different options exist. One option is to base the neighbourhood graph on neighbours that are in direct contact with each other (contiguous), as implemented in the poly2nb method.

annotGraph(sfe_tissue, "myofiber_poly2nb") <-
  findSpatialNeighbors(sfe_tissue,
                       type = "myofiber_simplified",
                       MARGIN = 3,
                       method = "poly2nb", # wraps spdep function with same name
                       zero.policy = TRUE
  )

p1 <- plotAnnotGraph(sfe_tissue,
                     annotGraphName = "myofiber_poly2nb",
                     annotGeometryName = "myofiber_simplified"
) + theme_void()

# Alternatively, we could take the five nearest neighbours of each cell.
annotGraph(sfe_tissue, "knn5") <-
  findSpatialNeighbors(sfe_tissue,
                       type = "myofiber_simplified",
                       MARGIN = 3, # to use the annotation geometry
                       method = "knearneigh", # wraps the spdep function with the same name
                       k = 5,
                       zero.policy = TRUE
  )

p2 <- plotAnnotGraph(sfe_tissue,
                     annotGraphName = "knn5",
                     annotGeometryName = "myofiber_simplified"
) + theme_void()

# As we can see below, the graphs look quite distinct. On the left side, in the contiguous neigbhbour graph (neighbours in direct contact), we notice the formation of patches, while in the NN graph isolated patches are interconnected.
p1 + p2

# Spatial autocorrelation -------------------------------------------------
# Spatial autocorrelation measures the association between spatial units while considering that these spatial units are not independent measurements. These measures can be global (summarizing the entire field) or local (providing statistics for individual locations) (Pebesma and Bivand 2023).

# Global Measures ---------------------------------------------------------
# Global methods give us an overview over the entire field-of-view and summarize the spatial autocorrelation metric to a single value. The metrics are a function of the weight matrix and the variables of interest. The variables of interest can be e.g. gene expression, intensity of a marker or the area of a cell. The global measures can be seen as a weighted average of the local metric, as explained below.

# In general, a global spatial autocorrelation measure has the form of a double sum over all locations 

# n <- length(x)
# total_sum <- 0
# 
# # The double summation translates to a double loop
# for (i in 1:n) {
#   for (j in 1:n) {
#     # Multiply the function output by the spatial weight
#     total_sum <- total_sum + ( f(x[i], x[j]) * W[i, j] )
#   }
# }

# `i` and `j` represent pairs of spots across the tissue lattice.
# x[i] and x[j] are the metrics measured at those spots (e.g., gene expression counts).
# where `f(x[i], x[j])` is the measure of association between features of interest (these changes base on the metric used, for example Morons'I or Geary's C) and `W[i, j]` scales the relationship by a spatial weight as defined in the weight matrix `W` (Zuur, Ieno, and Smith 2007; Pebesma and Bivand 2023).
# If you are calculating Moran's I (measuring global similarity), `f(x[i], x[j])` is defined as the cross-product of their deviations from the mean: `(x[i] - avg(x))(x[j] - avg(x))`.
# If you are calculating Geary's C (measuring spatial dissimilarity), `f(x[i], x[j])` is the squared difference between the two values: `(x[i] - x[j])^2`.

# Moran’s I ---------------------------------------------------------------
# is the most prominent measure of spatial autocorrelation. The values are bounded by -1 and 1. The expected value is close to 0 for large `n`, the exact value is given by `E(I) = -1/(n-1)`. A value higher than the expected value indicates spatial autocorrelation. Negative values indicate negative autocorrelation.
# Spatial autocorrelation means that similar values tend to be found together in the tissue. In fact, Moran’s I can be interpreted as the Pearson correlation between the value at location `i` and the averages value of the neigbours of `i`, (neighbours as defined in the weight matrix `W`) (Moran 1950; Cliff and Ord 1981, 21).

# In the first example we will calculate Moran’s I for the number of counts and genes measured in the Visium dataset. First, we have a look at the distribution by eye.
plotSpatialFeature(sfe_tissue,
                   features = features,
                   colGeometryName = "spotPoly",
                   swap_rownames = "symbol"
)

# Based on these values we can calculate Moran’s I
# notice the that the graph was generated with this methods
# colGraph(sfe_tissue, "visium") <- findVisiumGraph(sfe_tissue)
sfe_tissue <- runUnivariate(sfe_tissue,
                            type = "moran",
                            features = features,
                            colGraphName = "visium",
                            swap_rownames = "symbol"
)

# access the stimates of the Moran's I. this is added as metadata of the features
rowData(sfe_tissue)[rowData(sfe_tissue)$symbol %in% features,]

# notice that this has been calculated only for the variable requested
head(rowData(sfe_tissue))

# We can further use permutation testing to get a significance of our estimates.
listSFEMethods("uni", "global")
sfe_tissue <- runUnivariate(sfe_tissue,
                            type = "moran.mc",
                            features = features,
                            colGraphName = "visium",
                            swap_rownames = "symbol",
                            nsim = 100
)

rowData(sfe_tissue)[rowData(sfe_tissue)$symbol %in% features,]

# As we can see, the Moran’s I values both indicate significant positive spatial autocorrelation. Myh2 shows a stronger correlation according to Moran’s I than Calr.

# explain how it works ----------------------------------------------------
# Here is a step-by-step breakdown of exactly what type = "moran.mc" (Monte Carlo permutation for Moran's I) is doing under the hood:
# 1. Calculate the Observed Moran's I: 
# First, the algorithm calculates the actual Moran's I using your real data. It looks at the real gene expression of Myh2 at Spot 1, compares it to its real neighbors, and gets a baseline score. Let's say this observed score is 0.65 (indicating strong positive spatial correlation).
                                                                  
# 2. The Permutation (The "Shuffle"):
# Next, the algorithm takes all the observed gene expression values for Myh2. It leaves the empty spots (and their defined neighbor connections) exactly where they are on the lattice.
# Then, it randomly pulls values of expression and randomly assign them back onto the tissue slide.
# Because the values are assigned randomly, any biological "clumping" or spatial pattern is completely destroyed, but the overall distribution of the gene (the mean, the variance) remains identical.
# 3. Calculate the "Pseudo" Moran's I:
# Now, it recalculates Moran's I on this newly randomized tissue map. Because the data is randomly scattered, the Moran's I score should drop close to 0 (no spatial correlation).
# 4. Repeat nsim Times:
# The algorithm will shuffle the values and recalculate the "pseudo" Moran's I 100 different times. This builds a "null distribution".
# 5. Calculate the P-Value (Confidence):
# Finally, it compares your original, real Moran's I (0.65) to the 100 random scores.
# If the real score of 0.65 is higher than all 100 random scores, the p-value is < 0.01. The spatial clustering you see is almost impossible to achieve by random chance. Else, the observed pattern could easily just be noise.
# -------------------------------------------------------------------------

# Local Measures for Univariate Data --------------------------------------
# Often, a global measure is not enough. One number determining e.g. the spatial autocorrelation over an entire tissue slice might not be reflective of tissue heterogeneity. Therefore, local indicators of spatial associations have been developed (Pebesma and Bivand 2023; Anselin 1995).

# Local Moran’s I ---------------------------------------------------------
# Local Moran’s I provides a measure of spatial autocorrelation at each location, highlighting local clusters of similarity or dissimilarity (Anselin 1995; Pebesma and Bivand 2023). It is defined as:

# Given variables:
# x: vector of gene expression counts
# W: spatial weight matrix
# i: the specific spot index we are calculating the score for
# n: total number of spots (length(x))

# x_bar <- mean(x)
# n <- length(x)

# ---------------------------------------------------------
# 1. The Denominator: sum_{k=1}^n (x[k] - x_bar)^2 / (n - 1)
# ---------------------------------------------------------
# var_sum <- 0
# for (k in 1:n) {
#   var_sum <- var_sum + (x[k] - x_bar)^2
# }
# denominator <- var_sum / (n - 1)

# ---------------------------------------------------------
# 2. The Spatial Lag: sum_{j=1}^n W[i, j] * (x[j] - x_bar)
# ---------------------------------------------------------
# spatial_lag_sum <- 0
# for (j in 1:n) {
#   spatial_lag_sum <- spatial_lag_sum + (W[i, j] * (x[j] - x_bar))
# }

# ---------------------------------------------------------
# 3. Final Local Moran's I for spot 'i'
# ---------------------------------------------------------
# I_i <- ((x[i] - x_bar) / denominator) * spatial_lag_sum
  
# This formula calculates Local Moran's I (I_i) for a specific spot `i`. It measures the local spatial autocorrelation to identify local clusters or outliers.
# 1. `x[i] - x_bar`: 
# The deviation of our target spot `i` from the global mean (`x_bar`).
#
# 2. The denominator `sum_{k=1}^n (x[k] - x_bar)^2 / (n - 1)`:
# This represents the sample variance. In loop notation, it requires iterating an index `k` from 1 to `n` (across all spots in the dataset), squaring each spot's deviation from the mean, summing them, and dividing by `n - 1`.
#
# 3. The spatial lag `sum_{j=1}^n W[i, j] * (x[j] - x_bar)`:
# This represents the spatially weighted neighborhood sum. It requires iterating an index `j` from 1 to `n`. For every spot `j`, we multiply the spatial weight `W[i, j]` by spot `j`'s deviation from the mean, and add it to a running total. (If `i` and `j` are not neighbors, `W[i, j]` is 0, canceling that term out).
#
# Conceptual calculation for a single spot `i`:
# var_sum <- 0; for(k in 1:n) { var_sum <- var_sum + (x[k] - x_bar)^2 }
# lag_sum <- 0; for(j in 1:n) { lag_sum <- lag_sum + (W[i, j] * (x[j] - x_bar)) }
# I_i <- ((x[i] - x_bar) / (var_sum / (n - 1))) * lag_sum
  
# where the index `i` refers to the location for which the measure is calculated. The interpretation is analogous to global Moran’s I where a value of `I_i` higher than E(I_i) = -w[i]/(n-1) indicates spatial autocorrelation; smaller values indicate negative autocorrelation (Anselin 1995). It is important to note that, as for the global counterpart, the value of local Moran’s I could be a result from both the high or low end of the values. Here we will calculate the local Moran’s I value for the measurement of muscle fiber marker gene Myh2:
listSFEMethods("uni", "local")
sfe_tissue <- runUnivariate(sfe_tissue,
                            type = "localmoran",
                            features = "Myh2",
                            colGraphName = "visium",
                            swap_rownames = "symbol")

# the value are accessible here
localResultNames(sfe_tissue)

# this command gives all results of localmoran
localResultFeatures(sfe_tissue, "localmoran")

# extract the local values
localResult(sfe_tissue,"localmoran",feature = "Myh2",swap_rownames = "symbol")

dim(sfe_tissue)
localResult(sfe_tissue,"localmoran",feature = "Myh2",swap_rownames = "symbol") %>% dim()

# explanation -------------------------------------------------------------
# Statistics
# Ii: This is the exact Local Moran's $I_i$ value that our loop calculated for that specific spot. A positive value means the spot is similar to its neighbors; a negative value means it is a spatial outlier (different from its neighbors). It is expected to not be bound between -1 and 1. It should be contextualized with the p value associated to identify significant correlation values.

# E.Ii: The Expected $I_i$ value if there were absolutely no spatial correlation (usually a number very close to zero).

# Var.Ii: The Variance of the expected $I_i$ value under the null hypothesis.

# Z.Ii: The Z-score. This represents how many standard deviations your observed $I_i$ is away from the expected $I_i$. Higher absolute Z-scores mean stronger evidence of a non-random spatial pattern.

# Pr(z != E(Ii)): The raw p-value. If this is very low (e.g., < 0.05), the spatial pattern around that specific spot is statistically significant.

# The Spatial Classifications (LISA Quadrants)
# The columns mean, median, and pysal are where the algorithm categorizes each spot into a spatial "quadrant." The pysal column explicitly mirrors the categorization logic from the popular Python spatial library of the same name.High-High: A "hot spot." This spot has high Myh2 expression AND is surrounded by neighbors with high expression.Low-Low: A "cold spot." This spot has low expression AND is surrounded by neighbors with low expression.High-Low / Low-High: These are "spatial outliers." For example, High-Low means a spot has high expression but is entirely surrounded by neighbors with low expression.

# Visualization Helpers
# -log10p & -log10p_adj: These are mathematically transformed versions of your p-values (the latter being adjusted for multiple testing/FDR). Converting them to $-log_{10}$ scales makes them incredibly easy to plot on graphs, as a larger number now equals higher statistical significance.

# -------------------------------------------------------------------------

# plot the expression values
pExp <- plotSpatialFeature(sfe_tissue,
                           features = c("Myh2"),
                           colGeometryName = "spotPoly",
                           swap_rownames = "symbol"
)

# plot the local Moran's I values
pLi <- plotLocalResult(sfe_tissue, "localmoran",
                       features = c("Myh2"),
                       colGeometryName = "spotPoly", swap_rownames = "symbol",
                       divergent = TRUE, diverge_center = 0
) + labs(fill = "li(Myh2)") # specify legend


# plot the local Moran's I p-values
pPval <- plotLocalResult(sfe_tissue, "localmoran",
                         features = c("Myh2"),
                         attribute = "-log10p_adj",
                         colGeometryName = "spotPoly", swap_rownames = "symbol",
                         divergent = TRUE, diverge_center = -log10(0.05)
) + labs(fill = "-log10(p.adj)") # specify legend

# please note that the colour scales for plots 2 & 3 are different
pExp + pLi + pPval

plotLocalResult(sfe_tissue, "localmoran",
                features = c("Myh2"),
                attribute = "median",
                colGeometryName = "spotPoly", swap_rownames = "symbol",
                divergent = TRUE, diverge_center = -log10(0.05)
)

# In the local version of Moran’s I, the interpretation is the same as the global version. When interpreting local autocorrelation measures, it is important to consider both the effect size estimates and the significance level. Since the significance level is calculated for each spot separately, it is recommended to adjust for multiple testing. By default, runUnivariate uses the Benjamini & Hochberg correction (Benjamini and Hochberg 1995). The local Moran’s I statistics reveal locations in the tissue that have similar values to their neighbours (c.f., the lower part of the tissue).

# Multivariate measures – Bivariate Moran’s I -----------------------------
# There exists a bivariate version of Moran’s I as well.

# For two continuous observations the GLOBAL bivariate Moran’s I is defined as (Wartenberg 1985; Bivand 2022)

# Given variables (assuming they are already mean-centered):
# a: vector of expression counts for Gene A (e.g., Myh2)
# b: vector of expression counts for Gene B (e.g., Calr)
# W: spatial weight matrix
# n: total number of spots (length(a))

# ---------------------------------------------------------
# 1. The Denominator: sum_{i} (b[i]^2)
# ---------------------------------------------------------
# denominator_sum <- 0
# for (i in 1:n) {
#   denominator_sum <- denominator_sum + (b[i]^2)
# }
# ---------------------------------------------------------
# 2. The Numerator: sum_{i} ( sum_{j} (W[i,j] * b[j]) * a[i] )
# ---------------------------------------------------------
# numerator_sum <- 0
# 
# for (i in 1:n) {
#   
#   # Inner loop: calculate the spatial lag of 'b' for target spot 'i'
#   spatial_lag_b <- 0
#   for (j in 1:n) {
#     spatial_lag_b <- spatial_lag_b + (W[i, j] * b[j])
#   }
#   
#   # Multiply spot i's 'a' value by the spatial lag of 'b', and add to numerator sum
#   numerator_sum <- numerator_sum + (spatial_lag_b * a[i])
# }
# ---------------------------------------------------------
# 3. Final Bivariate Moran's I
# ---------------------------------------------------------
# I_B <- numerator_sum / denominator_sum

# This formula calculates the GLOBAL Bivariate Moran's I (I_B).
# It measures the spatial correlation between two DIFFERENT features (e.g., Gene A and Gene B).
#
# 1. The inner summation `sum_j (w[i,j] * b[j])`:
# This calculates the "spatial lag" for feature 'b' around our target spot 'i'. It iterates through all spots 'j', multiplying the spatial weight by the value of 'b'.
#
# 2. The numerator `sum_i ( [spatial_lag_b] * a[i] )`:
# It iterates through all target spots 'i', multiplying the value of feature 'a' at spot 'i' by the spatial lag of feature 'b' we just calculated, summing them all up.
#
# 3. The denominator `sum_i (b[i]^2)`:
# This represents the total variance of feature 'b'. It iterates through all spots,squaring the value of 'b' and adding it to a running total.

# where `ai` and `bi`are the two variables of interest and `wij` is the value of the spatial weights matrix for positions `i` and `j`. It is a measure of the correlation of the variables `a` with the average of the neighboring values for variable `b` (also called the spatial lag of `b`).
listSFEMethods("bi", "global")

# There exists a LOCAL version that we will explore here. Note that the results are not symmetric, but very similar to each other.

# explanation -------------------------------------------------------------
# This formula calculates Local Bivariate Moran's I (I_B,i) for a specific spot `i`.
# It measures if Gene A at spot `i` is correlated with Gene B in its surrounding neighbors.
#
# n <- length(z_A)

# ---------------------------------------------------------
# 1. The Spatial Lag: sum_{j=1}^n (W[i, j] * z_B[j])
# ---------------------------------------------------------
# spatial_lag_B <- 0
# 
# for (j in 1:n) {
#   # Multiply the neighbor's Gene B value by the spatial weight
#   spatial_lag_B <- spatial_lag_B + (W[i, j] * z_B[j])
# }
# ---------------------------------------------------------
# 2. Final Local Bivariate Moran's I for spot 'i'
# ---------------------------------------------------------
# Multiply target spot's Gene A value by the surrounding neighborhood's Gene B value
# I_Bi <- z_A[i] * spatial_lag_B

# Mathematical components:
# 1. `z_A[i]`: The standardized value (Z-score) of Gene A at our target spot `i`.
# 2. The summation `sum_{j=1}^n w[i,j] * z_B[j]`: This is the spatial lag of Gene B.
#    It iterates through all spots `j`, multiplying the spatial weight by the 
#    standardized value of Gene B, effectively calculating the neighborhood average.
#
# Assumptions:
# z_A and z_B are already standardized vectors (mean = 0, variance = 1).
# For example, in R you would do: z_A <- scale(Myh2); z_B <- scale(Calr)

# why the metric is asymmetric?
# To understand why this asymmetry is actually a massive advantage for spatial transcriptomics, imagine a tumor microenvironment:
# Gene A is a tumor marker.Gene B is an immune cell marker (like a T-cell).
# Imagine a single tumor cell (high Gene A, low Gene B) completely surrounded by a ring of attacking immune cells (low Gene A, high Gene B). Let's look at the target spot $i$ (the tumor cell) from both directions:
# Direction 1 ($A \to B$): The center spot has high Gene A. The neighbors have high Gene B.Result: High-High cluster. (Interpretation: "This tumor cell is surrounded by immune cells").
# Direction 2 ($B \to A$): The exact same center spot has low Gene B (it is a tumor cell, not an immune cell). The neighbors have low Gene A (they are immune cells, not tumor cells).Result: Low-Low cluster. (Interpretation: "This spot lacks immune cells, and its neighbors lack tumor cells").
# By being asymmetric, the local bivariate metric precisely captures the biological architecture—specifically, which cell type is sitting at the core and which cell type makes up the surrounding shell .
# -------------------------------------------------------------------------
listSFEMethods("bi", "local")
sfe_tissue <- runBivariate(sfe_tissue,
                           type = "localmoran_bv", # wraps the method from spdep
                           feature1 = "Myh1",
                           feature2 = "Myh2",
                           colGraphName = "visium",
                           swap_rownames = "symbol",
                           nsim = 100)

# the value are accessible here
localResultNames(sfe_tissue)

# this command gives all results of localmoran_bv
localResultFeatures(sfe_tissue, "localmoran_bv")

# access the actual values
localResult(sfe_tissue,"localmoran_bv",feature = "Myh1__Myh2")

# plot the values
plotLocalResult(sfe_tissue,
                name = "localmoran_bv",
                attribute = "Ibvi",
                features = c("Myh1__Myh2", "Myh2__Myh1"),
                colGeometryName = "spotPoly",
                divergent = TRUE,
                diverge_center = 0)

# Please note that the result might overestimate the spatial autocorrelation of the variables due to the inherent (non-spatial) correlation of `x` and `y` (Bivand 2022).

# explanation -------------------------------------------------------------
# what is the Inherent (Non-Spatial) Correlation?
# Imagine you are looking at two genes, Gene X and Gene Y. Biologically, they are tightly co-expressed. Whenever a cell turns on Gene X, it automatically turns on Gene Y.
# This is an inherent, non-spatial correlation. They are correlated simply because of the cell's internal biology, entirely regardless of where that cell is physically located on your tissue slide. If you ran a standard Pearson correlation on these two genes, the score would be very high.

# The Global Statistic Method
# Instead of counting local spots, calculate a single global statistic for the entire tissue for each pair.
# Calculate the Global Bivariate Moran's I for each pair. Rank the pairs by their global Z-score or permutation p-value.
# If two genes are highly co-expressed inside the exact same cells, standard Bivariate Moran's I will artificially inflate their spatial correlation. If you are comparing many pairs, it is highly recommended to calculate Global Lee's L instead, which mathematically separates the "in-cell" correlation from the "neighbor" correlation.

listSFEMethods("bi", "global")
calculateBivariate(sfe_tissue,
                   type = "lee", # wraps the method from spdep
                   feature1 = "Myh1",
                   feature2 = "Myh2",
                   colGraphName = "visium",
                   swap_rownames = "symbol",
                   nsim = 100)

calculateBivariate(sfe_tissue,
                   type = "lee.mc", # wraps the method from spdep
                   feature1 = "Myh1",
                   feature2 = "Myh2",
                   colGraphName = "visium",
                   swap_rownames = "symbol",
                   nsim = 100)
# -------------------------------------------------------------------------

# The package spatialDM (Li et al. 2023) uses an adapted version of bivariate Moran’s I to identify ligand-receptor pairs.

# test passing features ---------------------------------------------------
# passing directly in feature1 a vector will produce all the pariwise comparisons
rowData(sfe_tissue)
# pass only the feature 1 a vecotor
sfe_tissue <- runBivariate(sfe_tissue,
                           type = "localmoran_bv", # wraps the method from spdep
                           feature1 = c("Actb","Gapdh","Tcea1"),
                           colGraphName = "visium",
                           swap_rownames = "symbol",
                           nsim = 100)

# the value are accessible here
localResultNames(sfe_tissue)

# this command gives all results of localmoran_bv
localResultFeatures(sfe_tissue, "localmoran_bv")

# access the actual values
localResult(sfe_tissue,"localmoran_bv",feature = "Gapdh__Actb")

# -------------------------------------------------------------------------

# test local bivatiate correlation with metadata --------------------------
# the bivariate correlation can also be used with data in the metadata, not only with gene expression

# 1. Extract your spatial network
spatial_net <- colGraph(sfe_tissue,type = "visium")
# spatial_net <- spatialGraph(sfe_tissue, type = "myofiber_poly2nb",MARGIN = 3)

# 2. Extract the data vectors manually
# extract the gene expresison
rowData(sfe_tissue) %>%
  data.frame() %>%
  filter(symbol %in% c("Myh2"))
gene_x <- as.numeric(logcounts(sfe_tissue)["ENSMUSG00000033196", ])

# extract the covariate
colData(sfe_tissue)
covariate_y <- as.numeric(sfe_tissue$nCounts)

# 3. Feed the vectors directly into Voyager's calculator
bivariate_results <- calculateBivariate(
  x = gene_x, 
  y = covariate_y, 
  type = "localmoran_bv", 
  listw = spatial_net,
  nsim=100)

# View your results
head(bivariate_results)

# rename the column needed for the addition to the localResults
colnames(bivariate_results) <- "Myh2__nCounts"

# use the results for plotting
# 1. Inject the standalone results table back into the sfe_tissue object
# localResult(sfe_tissue, type = "localmoran_bv", feature = "x__y") <- bivariate_results
localResult(sfe_tissue, type = "localmoran_bv", feature = "Myh2__nCounts") <- bivariate_results

# confirm the addition
# this command gives all results of localmoran_bv
localResultFeatures(sfe_tissue, "localmoran_bv")
localResult(sfe_tissue, type = "localmoran_bv", feature = "Myh2__nCounts")

# 2. plot the results
plotLocalResult(sfe_tissue,
                name = "localmoran_bv",
                attribute = "Ibvi",
                features = c("Myh2__nCounts"),
                colGeometryName = "spotPoly",
                divergent = TRUE,
                diverge_center = 0)

# -------------------------------------------------------------------------

# Impact of neighbourhood on autocorrelation measures ---------------------
# Let’s compare the impact of different spatial weight matrices on local autocorrelation analysis. In this Visium dataset we do not have gene expression information for each cell because of the resolution of the spots. We will instead calculate the autocorrelation measures on the area of the segmented cells. This could be helpful when looking at local cell densities in a tissue.

# First, we base the spatial weight matrix on contiguous neighbours.
# The annotGeometryUnivariate() function works identically to the runUnivariate() function you used earlier, but instead of applying the math to the circular Visium spots (the regular lattice), it applies it to the annotated geometries—in this case, the myofiber_simplified polygons.

# area is a metric assigned to each individual unit defined in your network. Think of it like a three-layer cake:
# The Geometry (myofiber_simplified): This is the base layer. It is a collection of irregular, physically drawn polygons representing the segmented muscle cells.
# The Metric (area): This is the data attached to those shapes. It is simply the 2D physical footprint (the size) of each specific polygon.
# The Graph (myofiber_poly2nb): This is the network layered on top. Because these are irregular polygons (unlike the perfect grid of Visium spots), this graph calculates exactly which muscle fibers share a border and are physically touching one another.

sfe_tissue <- annotGeometryUnivariate(sfe_tissue,
                                      type = "localmoran",
                                      features = "area",
                                      annotGeometryName = "myofiber_simplified",
                                      annotGraphName = "myofiber_poly2nb",
                                      include_self = FALSE, zero.policy = TRUE,
                                      name = "myofiber_poly2nb")

# extract the values
myofibers <- annotGeometry(sfe_tissue, "myofiber_simplified")
colnames(myofibers)
myofibers$area

# plot
pPoly <- plotLocalResult(sfe_tissue,
                         name = "myofiber_poly2nb",
                         features = "area",
                         annotGeometryName = "myofiber_simplified",
                         annotGraphName = "myofiber_poly2nb",
                         divergent = TRUE, diverge_center = 0
) + labs(title = "Local Moran's I (li)\nContiguous Neighbours", 
         fill = "li(area)")

# As an alternative, we also base the spatial weight matrix on the 5 and 10 nearest neighbours.
sfe_tissue <- annotGeometryUnivariate(sfe_tissue,
                                      type = "localmoran",
                                      features = "area",
                                      annotGeometryName = "myofiber_simplified",
                                      annotGraphName = "knn5",
                                      include_self = FALSE, zero.policy = TRUE,
                                      name = "knn5")

pKnn5 <- plotLocalResult(sfe_tissue,
                         name = "knn5",
                         features = "area",
                         annotGeometryName = "myofiber_simplified",
                         annotGraphName = "knn5",
                         divergent = TRUE, diverge_center = 0) +
  labs(title = "Local Moran's I (li)\n5 Nearest Neighbours", 
         fill = "li(area)")

# create another graph knn10
annotGraph(sfe_tissue, "knn10") <- findSpatialNeighbors(sfe_tissue,
                                                        type = "myofiber_simplified",
                                                        MARGIN = 3, # to use the annotation geometry
                                                        method = "knearneigh", # wraps the spdep function with the same name
                                                        k = 10,
                                                        zero.policy = TRUE)

# calcualte the moran's I using the updated graph
sfe_tissue <- annotGeometryUnivariate(sfe_tissue,
                                      type = "localmoran",
                                      features = "area",
                                      annotGeometryName = "myofiber_simplified",
                                      annotGraphName = "knn10",
                                      include_self = FALSE, zero.policy = TRUE,
                                      name = "knn10")

pKnn10 <- plotLocalResult(sfe_tissue,
                          name = "knn10",
                          features = "area",
                          annotGeometryName = "myofiber_simplified",
                          annotGraphName = "knn10",
                          divergent = TRUE,
                          diverge_center = 0) +
  labs(title = "Local Moran's I (li)\n10 Nearest Neighbours", fill = "li(area)")

# plot the comparisons
pPoly + pKnn5 + pKnn10

# The overall pattern of spatial autocorrelation is similar across the different weight matrices. However, locally there are some differences, as well as in the scale of the autocorrelation (note that the same color in the different plots does not correspond to the same value between the plots). There is a trend of smoothing of the value, the larger the neighbourhood in consideration.

# Measures for categorical data -------------------------------------------
# There also exist methods to detect spatial autocorrelation of categorical variables. As we have no categorical measurements in this dataset, we perform non-spatial clustering using Leiden clustering on the PCA space (Traag, Waltman, and Van Eck 2019).

library(BiocNeighbors)
library(BiocSingular)

set.seed(123)
# Run PCA on the sample
sfe <- runPCA(sfe_tissue, exprs_values = "logcounts", ncomponents = 50, BSPARAM = IrlbaParam())
# Cluster based on first 20 PC's and using leiden
colData(sfe_tissue)$cluster <- clusterRows(reducedDim(sfe, "PCA")[,1:10],
                                           BLUSPARAM = KNNGraphParam(
                                             k = 20,
                                             BNPARAM=AnnoyParam(ntrees=50),
                                             cluster.fun = "leiden",
                                             cluster.args = list(
                                               resolution = 0.3,
                                               objective_function = "modularity")))

# We can visually inspect the spatial arrangement of the clusters. We see that they are spatially “clustered”.

plotSpatialFeature(sfe_tissue,
                   features = "cluster",
                   colGeometryName = "spotPoly")

# Metrics such as the join count statistics can be use to analysis spatial arrangements of categorical data. In essence, the join count statistic calculates the frequency of categories among neighbours and compares this value with a theoretical distribution or permutations of the labels to get a significance score (Cliff and Ord 1981).

# Here we will use an extension to multiple categories joincount.multi. The test gives information if the different clusters are in contact with itself and each other. The output shows the calculated number of contacts vs. the expected number, i.e., if the clusters were randomly assigned to the locations. The function does not report p-values, but they can be calculated at a specified significance level using the z-values.
joincount.multi(colData(sfe_tissue)$cluster,
                colGraph(sfe_tissue, "binary"))

# For example, we can see here that the calculated number of contacts of clusters 1 and 3 is far below the expected value. On the other hand all clusters are in contact with itself more often than expected at random.

# Therefore, in Python we add the lower triangular matrix to the upper triangle (without the diagonal) and divide the resulting interaction matrix by 2 as the interactions in R are undirected.

# Summary and Considerations ----------------------------------------------
# Lattice data refers to spatial data collected at fixed locations arranged in regular or irregular grids, contrasting with stochastic point pattern analysis.
# Regular lattices have uniform, evenly spaced spots, while irregular lattices have variable sizes and shapes with non-uniform spacing.
# The spatial weight matrix models spatial relationships between lattice units. Different methods exist to define the spatial weight matrix.
# Global spatial autocorrelation measures, like Moran’s I, summarize spatial correlation over the entire field, while local measures identify local clusters of similarity or dissimilarity.
# There exist measures of spatial autocorrelation for continuous and categorical data.
